version: "3.1"
services:
  wj_trucks_way_ui:
    build:
      context: .
    # command: ng serve --host 0.0.0.0
    container_name: wj_trucks_way_ui
    restart: always
    networks:
      - wayjournal-net
    ports:
      - "4200:80"

networks:
  wayjournal-net:

volumes:
  db-data:
