version: "3.1"
services:
  wj_trucks_way_ui:
    build:
      context: .
    # command: ng serve --host 0.0.0.0
    container_name: wj_trucks_way_ui
    restart: always
    links:
      - hls-vpn-proxy:hls
    networks:
      - wayjournal-net
    ports:
      - "80:80"

  hls-vpn-proxy:
    build:
      context: vpn-hls
    container_name: hls-vpn-proxy
    command: /root/run.sh --cap-add=NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    depends_on:
      - wj_trucks_way_ui
    environment:
      - no_proxy=ENV
      - ftp_proxy=ENV
      - http_proxy=ENV
      - https_proxy=ENV
    volumes:
      - vpn-hls/data/vpn/:/usr/vpnserver/
      - vpn-hls/data/nginx/:/etc/nginx/
      - vpn-hls/data/dhcp/:/etc/dhcp/
    restart: always
    networks:
      - wayjournal-net
    ports:
      - "81:80"
      - "8080:8080"
      - "443:443"
      - "992:992"
      - "1194:1194"
      - "5555:5555"

networks:
  wayjournal-net:

volumes:
  db-data:
