version: "3.1"
services:
  wj_trucks_way_ui:
    build:
      context: .
    # command: ng serve --host 0.0.0.0
    container_name: wj_trucks_way_ui
    restart: always
    links:
      - hls-vpn-proxy:hls
    networks:
      - wayjournal-net
    ports:
      - "80:80"

  hls-vpn-proxy:
    build:
      context: vpn-hls
    container_name: hls-vpn-proxy
    command: /root/run.sh
    devices:
      - "/dev/net/tun:/dev/net/tun"
    cap_add:
      - NET_ADMIN
    volumes:
      # - ./vpn-hls/data/vpn/:/usr/vpnserver/
      - ./vpn-hls/data/nginx/:/etc/nginx/
      - ./vpn-hls/data/dhcp/:/etc/dhcp/
    restart: always
    networks:
      - wayjournal-net
    ports:
      - "3000:80"
      - "5001:5555"

networks:
  wayjournal-net:
